title:
author:
email: arstone@g.harvard.edu
description: > # this means to ignore newlines until "baseurl:"
  Political Scientist and PhD Candidate, Harvard University. 

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
#github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
